name: gmlg3
channels:
  - rmg
  - pytorch
  - anaconda
  - conda-forge
  - conda-canary
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - alsa-lib=1.2.3
  - anyio=3.3.0
  - argon2-cffi=20.1.0
  - async_generator=1.10
  - attrs=21.2.0
  - babel=2.9.1
  - backcall=0.2.0
  - backports=1.0
  - backports.functools_lru_cache=1.6.4
  - bleach=4.1.0
  - boost=1.74.0
  - boost-cpp=1.74.0
  - brotlipy=0.7.0
  - bzip2=1.0.8
  - ca-certificates=2022.07.19
  - cairo=1.16.0
  - certifi=2022.6.15
  - cffi=1.14.6
  - chardet=4.0.0
  - charset-normalizer=2.0.0
  - cloudpickle=2.0.0
  - cpuonly=2.0
  - cryptography=3.4.7
  - cudatoolkit=11.1.1
  - cycler=0.10.0
  - dbus=1.13.6
  - debugpy=1.4.1
  - decorator=5.1.0
  - deepchem=2.6.1
  - defusedxml=0.7.1
  - descriptastorus=2.2.0
  - entrypoints=0.3
  - expat=2.4.1
  - fontconfig=2.13.1
  - freetype=2.10.4
  - future=0.18.2
  - gettext=0.19.8.1
  - glib=2.68.4
  - glib-tools=2.68.4
  - greenlet=1.1.1
  - gst-plugins-base=1.18.5
  - gstreamer=1.18.5
  - icu=68.1
  - idna=3.1
  - importlib-metadata=4.8.1
  - ipykernel=6.13.0
  - ipython=7.27.0
  - ipython_genutils=0.2.0
  - jbig=2.1
  - jedi=0.18.0
  - jinja2=3.0.1
  - joblib=1.0.1
  - jpeg=9d
  - json5=0.9.5
  - jsonschema=3.2.0
  - jupyter_client=7.0.3
  - jupyter_core=4.8.1
  - jupyter_server=1.11.0
  - jupyterlab=3.1.12
  - jupyterlab_pygments=0.1.2
  - jupyterlab_server=2.8.1
  - kiwisolver=1.3.2
  - krb5=1.19.2
  - lcms2=2.12
  - ld_impl_linux-64=2.36.1
  - lerc=2.2.1
  - libblas=3.9.0
  - libcblas=3.9.0
  - libclang=11.1.0
  - libdeflate=1.7
  - libedit=3.1.20191231
  - libevent=2.1.10
  - libffi=3.4.2
  - libgcc-ng=11.2.0
  - libgfortran-ng=11.2.0
  - libgfortran5=11.2.0
  - libglib=2.68.4
  - libiconv=1.16
  - liblapack=3.9.0
  - libllvm11=11.1.0
  - libogg=1.3.4
  - libopus=1.3.1
  - libpng=1.6.37
  - libpq=13.3
  - libprotobuf=3.16.0
  - libsodium=1.0.18
  - libstdcxx-ng=11.2.0
  - libtiff=4.3.0
  - libuuid=2.32.1
  - libvorbis=1.3.7
  - libwebp-base=1.2.1
  - libxcb=1.13
  - libxkbcommon=1.0.3
  - libxml2=2.9.12
  - llvm-openmp=12.0.1
  - lz4-c=1.9.3
  - markupsafe=2.0.1
  - matplotlib=3.4.3
  - matplotlib-base=3.4.3
  - matplotlib-inline=0.1.3
  - mistune=0.8.4
  - mkl=2021.3.0
  - mysql-common=8.0.25
  - mysql-libs=8.0.25
  - nbclassic=0.3.2
  - nbclient=0.5.4
  - nbconvert=6.1.0
  - nbformat=5.1.3
  - ncurses=6.2
  - nest-asyncio=1.5.1
  - networkx=2.8.4
  - ninja=1.10.2
  - notebook=6.4.4
  - nspr=4.30
  - nss=3.69
  - numpy=1.22.3
  - olefile=0.46
  - openjpeg=2.4.0
  - openssl=1.1.1q
  - packaging=21.0
  - pandas=1.4.2
  - pandoc=2.14.2
  - pandocfilters=1.5.0
  - parso=0.8.2
  - pcre=8.45
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pillow=8.3.2
  - pixman=0.40.0
  - prettytable=2.2.1
  - prometheus_client=0.11.0
  - prompt-toolkit=3.0.20
  - pthread-stubs=0.4
  - ptyprocess=0.7.0
  - pycairo=1.20.1
  - pycparser=2.20
  - pygments=2.10.0
  - pyopenssl=20.0.1
  - pyparsing=2.4.7
  - pyqt=5.12.3
  - pyqt-impl=5.12.3
  - pyqt5-sip=4.19.18
  - pyqtchart=5.12
  - pyqtwebengine=5.12.1
  - pyrsistent=0.17.3
  - pysocks=1.7.1
  - python=3.9.7
  - python-dateutil=2.8.2
  - python_abi=3.9
  - pytorch=1.9.0
  - pytorch-mutex=1.0
  - pytz=2021.1
  - pyzmq=22.3.0
  - qt=5.12.9
  - rdkit=2022.03.1
  - readline=8.1
  - reportlab=3.5.68
  - requests=2.26.0
  - requests-unixsocket=0.2.0
  - scikit-learn=1.0.2
  - scipy=1.7.1
  - send2trash=1.8.0
  - setuptools=58.0.4
  - six=1.16.0
  - sleef=3.5.1
  - sniffio=1.2.0
  - sqlalchemy=1.4.25
  - sqlite=3.36.0
  - tabulate=0.8.9
  - tbb=2021.3.0
  - terminado=0.12.1
  - testpath=0.5.0
  - threadpoolctl=2.2.0
  - tk=8.6.11
  - torchaudio=0.9.0
  - torchvision=0.2.2
  - tornado=6.1
  - traitlets=5.1.0
  - typing_extensions=4.2.0
  - tzdata=2021a
  - urllib3=1.26.6
  - wcwidth=0.2.5
  - webencodings=0.5.1
  - websocket-client=0.57.0
  - wheel=0.37.0
  - xorg-kbproto=1.0.7
  - xorg-libice=1.0.10
  - xorg-libsm=1.2.3
  - xorg-libx11=1.7.2
  - xorg-libxau=1.0.9
  - xorg-libxdmcp=1.1.3
  - xorg-libxext=1.3.4
  - xorg-libxrender=0.9.10
  - xorg-renderproto=0.11.1
  - xorg-xextproto=7.3.0
  - xorg-xproto=7.0.31
  - xz=5.2.5
  - zeromq=4.3.4
  - zipp=3.5.0
  - zlib=1.2.11
  - zstd=1.5.0
  - pip:
      - aiohttp==3.8.1
      - aiohttp-cors==0.7.0
      - aioredis==1.3.1
      - aiosignal==1.2.0
      - alabaster==0.7.12
      - alembic==1.7.4
      - async-timeout==4.0.1
      - autopage==0.4.0
      - autopep8==1.6.0
      - bayesian-optimization==1.2.0
      - blessings==1.7
      - cachetools==4.2.4
      - click==8.0.1
      - cliff==3.9.0
      - cmaes==0.8.2
      - cmd2==2.2.0
      - colorama==0.4.4
      - colorful==0.5.4
      - colorlog==6.5.0
      - configspace==0.4.20
      - cython==0.29.24
      - dgl==0.6.1
      - dgl-cu111==0.6.1
      - dglgo==0.0.1
      - dgllife==0.2.8
      - distlib==0.3.4
      - docutils==0.17.1
      - dragonfly-opt==0.1.6
      - filelock==3.6.0
      - frozenlist==1.2.0
      - google-api-core==2.2.2
      - google-auth==2.3.3
      - googleapis-common-protos==1.53.0
      - gpustat==0.6.0
      - grpcio==1.40.0
      - hiredis==2.0.0
      - hpbandster==0.7.4
      - hyperopt==0.2.7
      - imagesize==1.3.0
      - isort==5.10.1
      - mako==1.1.5
      - msgpack==1.0.2
      - multidict==5.2.0
      - mypy-extensions==0.4.3
      - netifaces==0.11.0
      - numpydoc==1.2.1
      - nvidia-ml-py3==7.352.0
      - opencensus==0.8.0
      - opencensus-context==0.1.2
      - optuna==2.10.0
      - patsy==0.5.1
      - pbr==5.6.0
      - pip==22.0.4
      - platformdirs==2.5.1
      - protobuf==3.18.0
      - psutil==5.8.0
      - py-spy==0.3.11
      - py4j==0.10.9.5
      - pyasn1==0.4.8
      - pyasn1-modules==0.2.8
      - pycodestyle==2.8.0
      - pydantic==1.9.0
      - pyperclip==1.8.2
      - pyro4==4.81
      - pyyaml==5.4.1
      - ray==1.12.0
      - redis==3.5.3
      - rsa==4.7.2
      - ruamel-yaml==0.17.21
      - ruamel-yaml-clib==0.2.6
      - serpent==1.40
      - snowballstemmer==2.2.0
      - sphinx==4.5.0
      - sphinxcontrib-applehelp==1.0.2
      - sphinxcontrib-devhelp==1.0.2
      - sphinxcontrib-htmlhelp==2.0.0
      - sphinxcontrib-jsmath==1.0.1
      - sphinxcontrib-qthelp==1.0.3
      - sphinxcontrib-serializinghtml==1.1.5
      - statsmodels==0.12.2
      - stevedore==3.5.0
      - tensorboardx==2.5
      - toml==0.10.2
      - tqdm==4.62.3
      - typed-argument-parser==1.7.1
      - typer==0.4.1
      - typing-inspect==0.7.1
      - virtualenv==20.14.1
      - yarl==1.7.2
